### ISSUE TITLE
Support Numpy >=1.24

### ISSUE THREAD

**Issue by SimonBoothroyd** [compsciencelab/pytorchrl#4]
As of numpy 1.24, aliases for builtin types such as `numpy.bool` and `numpy.int` have been removed (see [`1.20` release notes](https://github.com/numpy/numpy/releases/tag/v1.24.0) and [`1.24` release notes](https://github.com/numpy/numpy/releases/tag/v1.20.0)). This repo still uses these in a few places and so is incompatible with newer numpy releases.

**Comment by albertbou92** [comment]
Hello! I Just created a new branch to address the issue. Thanks you.
