### ISSUE TITLE
Obstacle Tower Example

### ISSUE THREAD

**Issue by Keboland108** [compsciencelab/pytorchrl#9]
Hi, 

Just wanted to say thanks for maintaining this repo. The overall goal, structural consistency of the examples and conceptual diversity are pretty awesome. 

While working through the examples, I attempted to install obstacle-tower-env according to:
```code
    cd
    wget https://github.com/Unity-Technologies/obstacle-tower-env/archive/v2.2.zip
    unzip v2.2.zip
    rm v2.2.zip
    cd obstacle-tower-env-2.2
    pip install -e .

    wget https://storage.googleapis.com/obstacle-tower-build/v2.2/obstacletower_v2.2_linux.zip
    unzip obstacletower_v2.2_linux.zip
    pip install mlagents-envs==0.6.2
```

It seems version 2.2 is somewhat outdated and causes issues with a number of packages 

For example (at least for me) only python 3.7 works on Ubuntu 22.04. Also, trying to upgrade numpy leads to a circular package dependency issue similar to what can be seen here.  

``` console 
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gym 0.22.0 requires cloudpickle>=1.2.0, but you have cloudpickle 0.8.1 which is incompatible.
gymnasium 0.28.1 requires cloudpickle>=1.2.0, but you have cloudpickle 0.8.1 which is incompatible.
ray 2.5.0 requires protobuf!=3.19.5,>=3.15.3, but you have protobuf 3.6.1 which is incompatible.
Successfully installed numpy-1.21.5
```

I was able to get everything working eventually, but not after heavy environment modification. The conda environment can be found at the following link [environment](https://gist.github.com/Keboland108/5ca6519752ff2e688ddccac7c1fc1212) 

Is there a recommend python version / configuration for running the examples?

**Comment by albertbou92** [comment]
Hello! Thanks a lot for pointing it out and for sharing the environment.
We definitely need to update the dependencies to make the code work with recent versions of gym and python. 
I will try to address the issue in the coming weeks :)
